### ISSUE TITLE
Word wrap required for translations that are too long

### ISSUE THREAD

**Issue by dy2288** [First-Peoples-Cultural-Council/fv-games#10]
https://fv.nuxeocloud.com/explore/FV/sections/Data/Haida/Hlg%CC%B1aagilda%20X%CC%B1aayda%20Kil/Hlg%CC%B1aagilda%20X%CC%B1aayda%20Kil/play/wordsearch

**Comment by CharlieBodman** [comment]
Will knock these off tomorrow night
