### ISSUE TITLE
Picture not displaying and audio not playing.

### ISSUE THREAD

**Issue by dy2288** [First-Peoples-Cultural-Council/fv-games#8]
See https://fv.nuxeocloud.com/explore/FV/sections/Data/c%CC%95i%C5%A1aa%CA%94at%E1%B8%A5/Nuu%C4%8Daan%CC%93u%C9%AB/c%CC%95i%C5%A1aa%CA%94at%E1%B8%A5/play/wordsearch

**Comment by dy2288** [comment]
Most likely not an issue with the game itself, but with the data being fed in.

**Comment by CharlieBodman** [comment]
Yeah, looks like config is passing in undefined audio and images

`"audio":"https://fv.nuxeocloud.com/nuxeo/undefined?inline=true"`
`"image":"https://fv.nuxeocloud.com/nuxeo/undefined?inline=true"`
